### ISSUE TITLE
Create a preliminary version of a pediatric template

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/pediatric-template#3]
Few notes:
- Template would need to be created for the T1w and T2w contrasts.
- They need to be coregistered. Our template creation pipeline includes this (eg used for PAM50).
- Data are already stitched: 
  - T1w: `sub-101_rec-composed_T1w.nii.gz`
  - T2w: `sub-101_rec-composed_T2w.nii.gz`

What to do:
- [ ] Segment spinal cord
- [ ] QC the segmentation and stitched data
- [ ] Label discs (look at the template creation pipeline for details of the expected labels).
- [ ] Run template creation pipeline. Re-use code from https://github.com/sct-pipeline/exvivo-template

Technical details:
- put the scripts under `scripts/`
- use `sct_run_batch` so it creates log files and QC files etc.

**Comment by joshuacwnewton** [comment]
@jcohenadad I'm not quite sure which dataset "Stitch volumes together" is referring to. 

(There isn't a mention of, say, `duke` in the README.md of this repo? The closest thing I see is an [`example_data` OSF link](https://github.com/sct-pipeline/pediatric-template/blob/9d85f6c6af2844726d7a8cd82635e153ddf265c1/preprocessing.py#L53-L54) mentioned in #1, but all of the `errsm` subjects seem to be single images already (e.g. `t2.nii.gz`), rather than multi-volume sets.)

Is there a specific pediatric dataset that needs to be stitched?

**Comment by jcohenadad** [comment]
sorry @joshuacwnewton i was actually writing this issue for the dog template and then realized i was in the wrong repository-- doing too many things in parallel 😅 -- i've edited the issue tasks

**Comment by rohanbanerjee** [comment]
The objective of this issue has been solved. Closing this therefore.
